artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/CodeofRahul/Dataset/raw/refs/heads/main/books_data.zip
  dataset_dir: dataset
  ingested_dir: ingested_data/books_data
  raw_data_dir: raw_data



data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: books.csv
  ratings_csv_file: ratings.csv



data_transformation_config:
  transformed_data_dir: transformed_data